# Generated by Django 5.2.5 on 2025-10-03 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='ranking',
            new_name='rank',
        ),
    ]
